# Generated by Django 4.2.11 on 2024-04-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('cvv', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=19)),
                ('address', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=6)),
                ('zipcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
