# Generated by Django 4.2.11 on 2024-04-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuser',
            old_name='user',
            new_name='email',
        ),
    ]
